matrix:
  include:
    - language: python
      python:
        - 3.6.5
      install:
        - pip install -r requirements.txt
      script:
        - coverage run --source=./app -m pytest -v --disable-pytest-warnings
      after_success:
        - coveralls
